[package]
name = "denvis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cpal = "0.15.2"
crossbeam = "0.8.4"
femtovg = "0.13.0"
glutin = "0.32.1"
glutin-winit = "0.5.0"
resource = "0.5.0"
rustfft = "6.2.0"
serde = "1.0.171"
winit = "0.30.0"
#winit = { git = "https://github.com/TheAlan404/winit.git", branch = "transrights" }

[patch.crates-io]
#winit = { git = "https://github.com/TheAlan404/winit.git", branch = "ihatedeps" }
